version: '3'
services:
  database:
    image: "kjconroy/sqlc"
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - go-gqlgen-sqlc-example:/var/lib/postgresql/data/


volumes:
  go-gqlgen-sqlc-example:
